platform :ios, '8.0'
use_frameworks!

target 'GitHubClient_Example' do
  pod 'GitHubClient', :path => '../'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'SwiftyImage'
  pod 'DynamicColor'
  pod 'SwiftyBeaver'
  pod 'MBProgressHUD'
  pod 'SideMenu'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'GitHubClient_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
