#source 'https://github.com/ZHocean123/Specs.git'
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'GitHubClient_Example' do
  pod 'GitHubClient', :path => '../'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'DynamicColor'
  pod 'XCGLogger'
  pod 'MBProgressHUD'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'CFNotify'
  pod 'RxSwift'
  pod 'Reusable'
  pod 'EFMarkdown'
  pod 'YYText'
  pod 'URLNavigator'
  pod 'MJRefresh'
  pod 'Texture'

  target 'GitHubClient_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
